# This is a config for E2B sandbox template.
# You can use template ID (2q2vio1lq9b19x7y3oro) or template name (k2vibe) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("k2vibe") # Sync sandbox
# sandbox = await AsyncSandbox.create("k2vibe") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('k2vibe')

team_id = "9559d3c9-72c3-4498-b3de-76ba245a1eb5"
dockerfile = "e2b.Dockerfile"
template_name = "k2vibe"
template_id = "2q2vio1lq9b19x7y3oro"
